### ISSUE TITLE
Have you successfully combined any baseline grid tools with Concise?

### ISSUE THREAD

**Issue by mhauer** [ConciseCSS/concise.css#267] opened 2017-02-06 14:44 UTC
I'm trying to add a good baseline grid, but most mixins and stuff are in the way of Concise or the other way around?

Thanks!

**Comment by jameskolce** [comment] 2017-02-06 23:39
Hi @mhauer 

Good question, let me explain what's the thing with those kinds of grids.

I am also a designer, and I think the idea of using grids everywhere on traditional graphic design is the right thing to do. However, I don't consider that to be useful for web design (column grids—like the one included in the framework—are great though).

When you have a design on paper you have the whole thing in front of your eyes, so everything has to be carefully aligned because is easy to spot any issue. But on the web, we have to scroll to see the whole content and the fluid nature of the displays (hundreds of them) makes impossible to make any assumptions and makes really hard to spot little alignment issues too.

One of the main problems with using a baseline grid for a whole page is that you have to have pixel perfection everywhere. If you leave one element with just one extra pixel, you might end up with big misalignments when you use that element several times. It is like a bridge, [if you start with 1mm to one side, you might end up with several meters of misalignment at the other end](http://www.snopes.com/wordpress/wp-content/uploads/2016/06/misaligned-bridge.jpg). And the problem is that you can't really control the height of all the elements *at every device size*.

If you want to have good *vertical rhythm* on your websites I would recommend to stop worrying about the height of the elements and just take care of the space between the elements; if you have consistent spacing you don't need anything else. For that, Concise includes the `lh` unit, which is the equivalent to the line-height in your CSS. See the **LH Unit** section of the docs: http://concisecss.com/documentation/#language-additions And because the line height also applies to text, you get aesthetic results without too much effort.

All this is just an advice though, I have been thinking a lot about it, and that's my conclusion. But I would like to know if you disagree with what I have said, perhaps I'm forgetting something and turns out I could add a new tool to the framework :)

**Comment by mhauer** [comment] 2017-02-07 08:30
I think I know where you’re coming from and I’d love to agree, but it’s not that simple.

A couple of issues:

* a different font size will break the rhythm, as you’re always using a relative line height
* as soon as you have grids and boxes next to each other you’ll see the different baselines if they have different font sizes
* i don’t need a fixed baseline for the whole page necessarily, just for specific areas

I’ve tried to use http://megatype.studiothick.com <http://megatype.studiothick.com/> yesterday, but couldn’t get it to work. More info: https://medium.com/@tbredin/a-jolly-web-typesetting-adventure-42948ab0d1dd#.eef5kdsoq <https://medium.com/@tbredin/a-jolly-web-typesetting-adventure-42948ab0d1dd#.eef5kdsoq>

**Comment by jameskolce** [comment] 2017-02-07 08:59
Yeah, I have seen Megatype before and have read that article (and several other solutions too) but I never found a justification for such complexity.

But could you send more details, like the result you are getting? Perhaps the problem is not related to Megatype.

**Comment by mhauer** [comment] 2017-02-07 09:05
I'm all about simplicity. If there is an easier solution...

One example from the Concise site. See this image
<img width="695" alt="screen shot 2017-02-07 at 10 02 05" src="https://cloud.githubusercontent.com/assets/577976/22684438/a8c3d972-ed1c-11e6-8532-0b32dae07631.png">

With Megatype  "Getting started" and "Using NPM" would be aligned on the same line.

If that's easier to solve great!

**Comment by jameskolce** [comment] 2017-02-07 09:27
I would love to have a simpler way to fix those kinds of things because I agree that it would be more aesthetic, but most of the time I don't bother with them (like in that screenshot you sent) because it gets too tedious and my time is limited.

There are tools like Megatype that try to fix those issues, but something is not quite right with them, all the solutions I have seen are like building castles over sand; I think the problem should be tackled on a lower level.

Right now I'm starting to build the next Concise CSS, and it is going to be a complete preprocessor instead of a framework, I want to implement features from a design point of view, instead of a developer point of view like all the current solutions (Sass, etc). Perhaps we could come up with a better solution and I could implement it, but it would have to be an elegant solution, so I can justify the effort.

Also, I have a project in mind to design a new language to replace CSS (the browser would still interpret CSS but that would be transparent for developers), and this new language won't have the limitations of CSS. I still don't know how feasible that is because it is just in my mind, but at least I know is possible (I have seen it). So if at some moment you think there is a good approach for this but needs some "dynamic" processes, then I could do it here. That would take a lot of time though, but I wanted to mention it so you know that if there is a good solution it could be implemented eventually even if is not possible with plain CSS (and Sass, less, stylus, etc).

I will start to think about all this, I will post something here if I get something, feel free to do the same if you get some ideas!

**Comment by jameskolce** [comment] 2017-02-07 10:25
Just tried something really quick. Setting the type ratio included in Concise with the value of the line height will generate proportional font sizes that will fit with the page baseline automatically (using the right margins).

![image](https://cloud.githubusercontent.com/assets/2559808/22686694/5b5562ee-ece2-11e6-9f71-a7ffc56bfdbb.png)

But because browsers don't consider the actual font baseline, we get that little space difference; the descender lines of the font are the ones aligned. To fix that in an elegant way we would have to get the real baseline of the font and match it with the document baseline. I have read about that before, so I'll check it out tomorrow with more time, it's 3:25AM right now 😅

**Comment by jameskolce** [comment] 2017-02-07 10:29
By the way, by doing that we lose the possibility to adjust the font sizes freely, to preserve that freedom we would have to adjust the margins or the line-heights accordingly. Tomorrow I'll think more about it, I think there could be a direct relation that can be adjusted automatically (but I'm not sure yet).

**Comment by mhauer** [comment] 2017-02-07 12:46
Nice! I guess the one topic is cap-height which solves for the actual font baseline. Thanks for continuing to look into it.

**Comment by jameskolce** [comment] 2017-11-30 03:14
(Will look further into this with the new Concise, closing for now)

**Closed by jameskolce** 2017-11-30 03:14 UTC
